package com.project.optrabidz.governance.application.common;

public enum GovernanceRuleCode {
    ALLOWED,
    ACCOUNT_NOT_FOUND,
    ROLE_MISMATCH,
    ACCOUNT_NOT_ACTIVE,
    PROFILE_INCOMPLETE,
    STARTUP_ACTOR_NOT_FOUND,
    INVESTOR_ACTOR_NOT_FOUND,
    STARTUP_CLASSIFICATION_REQUIRED,
    INVESTOR_PREFERENCE_REQUIRED,
    ADMIN_AUTHORITY_REQUIRED,
    RECOVERY_MODE_REQUIRED,
    NEUTRALITY_VIOLATION,
    SYSTEM_BOUNDARY_VIOLATION,
    LIFECYCLE_RULE_SKIPPED,
    LIFECYCLE_RULE_FAILED
}
