package com.project.optrabidz.financial.application.dto.response;

public enum PaymentTimelineStage {
    PAYMENT_INTENT_CREATED,
    PAYMENT_ATTEMPT_CREATED,
    DEMO_CHECKOUT_AVAILABLE,
    COLLECTION_CONFIRMED,
    COLLECTION_FAILED,
    COLLECTION_CANCELLED,
    SIMULATED_ESCROW_CREDIT,
    PAYOUT_WAITING_FOR_DESTINATION,
    PAYOUT_PENDING,
    PAYOUT_PROCESSING,
    PAYOUT_FAILED,
    PAYOUT_CONFIRMED,
    SETTLEMENT_CONFIRMED,
    INSTALLMENT_PAID
}
